#### **Connect to DuckDB & Query Summary Statistics**

In [1]:
import duckdb
import pandas as pd

# Connect to DuckDB database
db_path = "../data/energy_transition.db"
conn = duckdb.connect(db_path)

# Test query: Check available tables and row counts
tables = conn.execute("SHOW TABLES;").fetchall()
print("Tables in DuckDB:", tables)

# Query latest available year's generation mix for Ethiopia as a test
query = """
    SELECT Clean_Country, Year, "Electricity source", "Generation (TWh)", "Share of generation (%)"
    FROM ember_data
    WHERE Clean_Country = 'Ethiopia' AND Year = 2024
    ORDER BY "Generation (TWh)" DESC;
"""

df_test = conn.execute(query).df()
print("\nTest Query Result (Ethiopia - 2024 Generation Mix):")
display(df_test.head(10))

# Close connection
conn.close()

Tables in DuckDB: [('ember_data',), ('world_bank_data',)]

Test Query Result (Ethiopia - 2024 Generation Mix):

,Clean_Country,Year,Electricity source,Generation (TWh),Share of generation (%)
0,Ethiopia,2024,Renewables,25.20,100.000
1,Ethiopia,2024,Clean,25.20,100.000
2,Ethiopia,2024,Total generation,25.20,100.000
3,Ethiopia,2024,"Hydro, bioenergy and other renewables",24.46,97.063
4,Ethiopia,2024,Hydro,24.42,96.905
5,Ethiopia,2024,Demand,23.44,93.016
6,Ethiopia,2024,Wind and solar,0.74,2.937
7,Ethiopia,2024,Wind,0.70,2.778
8,Ethiopia,2024,Solar,0.04,0.159
9,Ethiopia,2024,Other renewables,0.03,0.119

#### **Prototype Core Technology Mix & Aggregate Filtering**

In [2]:
import duckdb

conn = duckdb.connect("../data/energy_transition.db")

query_tech_breakdown = """
    SELECT 
        Clean_Country,
        Year,
        "Electricity source",
        "Generation (TWh)",
        "Share of generation (%)"
    FROM ember_data
    WHERE Year = 2024 
      AND "Is aggregated source" = 0  -- Filters for specific disaggregated technologies
    ORDER BY Clean_Country, "Generation (TWh)" DESC;
"""

df_tech = conn.execute(query_tech_breakdown).df()
print(f"Disaggregated Tech Records for 2024: {len(df_tech)}")
display(df_tech.head(15))

conn.close()

Disaggregated Tech Records for 2024: 97

,Clean_Country,Year,Electricity source,Generation (TWh),Share of generation (%)
0,Egypt,2024,Gas,192.98,81.292
1,Egypt,2024,Other fossil,17.83,7.511
2,Egypt,2024,Hydro,14.37,6.053
3,Egypt,2024,Wind,6.14,2.586
4,Egypt,2024,Solar,6.07,2.557
5,Egypt,2024,Bioenergy,0.00,0.000
6,Egypt,2024,Coal,0.00,0.000
7,Egypt,2024,Net imports,-1.40,-0.590
8,Ethiopia,2024,Hydro,24.42,96.905
9,Ethiopia,2024,Wind,0.70,2.778
10,Ethiopia,2024,Solar,0.04,0.159
11,Ethiopia,2024,Other renewables,0.03,0.119
12,Ethiopia,2024,Bioenergy,0.01,0.040
13,Ethiopia,2024,Nuclear,0.00,0.000
14,Ethiopia,2024,Coal,0.00,0.000